// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wstxbmgesgeqbgjqpvmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzdHhibWdlc2dlcWJnanFwdm1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NDE3NTMsImV4cCI6MjA2OTQxNzc1M30.v0Au456ZqfnCA-MnDDsnoqHdjKUtlQ8yz4iQqhOb7p0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});